[project]
name = "rtfm-rag"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "aiohttp>=3.12.7",
    "beautifulsoup4>=4.13.4",
    "boto3>=1.38.33",
    "boto3-stubs[s3]>=1.42.44",
    "fastapi[standard]>=0.115.12",
    "html2text>=2025.4.15",
    "mcp[cli]>=1.13.1",
    "ollama>=0.6.0",
    "openai>=1.83.0",
    "psycopg[binary,pool]>=3.2.9",
    "pydantic-settings>=2.9.1",
    "result>=0.17.0",
    "tiktoken>=0.9.0",
]

[dependency-groups]
dev = [
    "dash>=3.0.4",
    "pandas>=2.3.0",
    "plotly>=6.1.2",
    "pytest>=8.4.1",
    "umap-learn>=0.5.7",
]


[tool.basedpyright]
reportUnusedVariable = "hint"
reportUnusedCallResult = false
reportAny = false
reportExplicitAny = false

[tool.ruff]
indent-width = 2

[tool.ruff.lint]
select = ["A", "ANN", "ASYNC", "B", "C4", "D", "E", "ERA", "F", "G", "I", "ICN", "N", "PERF", "PL", "PT", "PTH", "RET", "RUF", "S", "SIM", "T10", "T20", "TID"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D107", "D213", "D203", "E501", "S311"]
flake8-tidy-imports.ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
"scripts/**.py" = ["T201"]
"tests/**.py" = ["ERA001"]
